### ISSUE TITLE
libmbsystrace progress tracker

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/DualBootPatcher#1344]
- [ ] Development
  - [x] Complete libmbsystrace library code
  - [x] Complete libmbsystrace tests
  - [ ] Implement arch-specific hacks
    - [x] aarch64 - the syscall number post-`execve` is zeroed out
  - [ ] Push latest code to `libmbsystrace` branch
- [ ] Testing
  - [x] Local execution of unit tests
    - [x] Survives 10,000 sequential runs
  - [ ] qemu execution of arm unit tests
    - [ ] Survives 1 run with `-smp 1`
    - [ ] Survives 1 run with `-smp 4`
    - [ ] Survives 1,000 sequential runs with `-smp 1`
    - [ ] Survives 1,000 sequential runs with `-smp 4`
  - [ ] qemu execution of aarch64 unit tests
    - [x] Survives 1 run with `-smp 1`
    - [x] Survives 1 run with `-smp 4`
    - [ ] Survives 1,000 sequential runs with `-smp 1`
    - [ ] Survives 1,000 sequential runs with `-smp 4`
  - [ ] qemu execution of x86 unit tests
    - [ ] Survives 1 run with `-smp 1`
    - [ ] Survives 1 run with `-smp 4`
    - [ ] Survives 1,000 sequential runs with `-smp 1`
    - [ ] Survives 1,000 sequential runs with `-smp 4`
  - [ ] qemu execution of x86_64 unit tests
    - [ ] Survives 1 run with `-smp 1`
    - [ ] Survives 1 run with `-smp 4`
    - [ ] Survives 1,000 sequential runs with `-smp 1`
    - [ ] Survives 1,000 sequential runs with `-smp 4`
- [ ] Infrastructure
  - [ ] Build debian-based images for qemu testing (need kernel modules and busybox stuffed into initramfs)
  - [ ] Add prebuilts to `thirdparty/CMakeLists.txt`
  - [ ] Add init script for test execution within qemu
  - [ ] Add CMake targets for running tests within qemu
  - [ ] Add CMake targets for running qemu with busybox dev shell
  - [ ] Add qemu to docker images
  - [ ] Update CI to run tests within qemu
